### ISSUE TITLE
How to update website?

### ISSUE THREAD

**Issue by Skivling** [stevenengler/no-js-hugo-theme#4]
I have a website that uses this theme and have realised it has been updated. How should I go about updating my website? Do I just download + copy/paste into the themes folder, or is there other stuff I need to do?

For reference, my website is [skivling.codeberg.page](https://skivling.codeberg.page) and the repo is at [Codeberg](https://codeberg.org/Skivling/personal_website).

**Comment by stevenengler** [comment]
In general you should be able to just delete everything from `themes/no-js/` and replace it with the new files from this repository. But since you made some [changes](https://codeberg.org/Skivling/personal_website/commits/branch/main/themes/no-js) to the theme in `themes/no-js/`, you'll need to re-add those changes to the new theme files.

**Comment by stevenengler** [comment]
In general you should be able to just delete the old theme from `themes/no-js/`, replace it with the new files from this repository, then run hugo to regenerate the site. There isn't anything in particular that you'll need to change. For example the config toml options are still the same (I added a new optional `onionLocation` option). The latest changes are mostly css changes, and a small bug fix.

But since you made some custom [changes](https://codeberg.org/Skivling/personal_website/commits/branch/main/themes/no-js) to the theme in `themes/no-js/`, you'll need to re-add those changes to the new theme files. You can run `git diff be8501c2b8 themes/no-js/` to see the changes that you've made. None of your changes conflict with changes I've made, so it should be easy to re-add your changes.

If you have any questions or issues, let me know!

If you want to make it easy to update in the future, one option is to use a git submodule. You could make a fork of the theme in a new repository and add your custom changes there. Then you could add your forked theme as a submodule in the "personal_website" repository. When there are new changes to the theme, you could just rebase your fork and keep your custom changes, then update the git submodule. There can be disadvantages to git submodules as well, but it's an option.

**Comment by Skivling** [comment]
It messed some things up, it removed the link to the js file entirely and removed some apostrophes. Also removed the footer bar + text.
Commit: [bed65b37ba](https://codeberg.org/Skivling/personal_website/commit/bed65b37ba1bc445fe0a8bbb45e202a061a73724)

I just removed the old folder, git cloned it and renamed the folder to `no-js` as it was before.

**Comment by stevenengler** [comment]
You have both a `config.toml` and a `hugo.toml` in your repository. You should remove the `hugo.toml` and rename your `config.toml` to `hugo.toml`.

https://gohugo.io/getting-started/configuration/#configuration-file

> With v0.109.0 and earlier the basename of the site configuration file was `config` instead of `hugo`. You can use either, but should transition to the new naming convention when practical.

Previously your Hugo version was reading the `config.toml`, and now it's reading the `hugo.toml` which is missing a bunch of options like your footer text.

**Comment by Skivling** [comment]
Ok, thanks!

**Comment by stevenengler** [comment]
@Skivling Just letting you know I made one more change, this time to fix the cut-off font descender in the header links.

Example (the bottom of the "g" was cut off):

![1713219940_grim](https://github.com/stevenengler/no-js-hugo-theme/assets/3708797/b70951bb-86a6-4287-b426-5396d6d1c9fb)
